const run = async () => {}

run().catch((err) => console.error(err))
